FROM node:lts-alpine as build-step
RUN mkdir -p /app
WORKDIR /app
COPY package.json /app
RUN npm install
COPY . /app
RUN npm run build --prod

FROM docker.io/nginx:stable
COPY --from=build-step /app/dist/production /usr/share/nginx/html

RUN chown -R 1001:0 /var/cache/nginx /var/run /var/log/nginx /usr/share/nginx /run
RUN chmod -R ug+rwX /usr/share/nginx /var/cache/nginx /var/log/nginx /var/run /run
RUN sed -i.bak 's/listen\(.*\)80;/listen 8080;/' /etc/nginx/conf.d/default.conf
RUN sed -i.bak 's/^user/#user/' /etc/nginx/nginx.conf

EXPOSE 8080
EXPOSE 8443

USER 1001

CMD ["/bin/sh",  "-c",  "envsubst < /usr/share/nginx/html/assets/env.template.js > /usr/share/nginx/html/assets/env.js && exec nginx -g 'daemon off;'"]
